# Site
repository: ArmanTursun/cv
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Arman Tursun
#title:
phone: +81 080-3099-0424
email: arman@g.ecc.u-tokyo.ac.jp
# address: 2-30-15, Hongo, Bunkyo-ku, Tokyo, Japan
website: https://github.com/ArmanTursun

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  ArmanTursun
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
facebook_username: arman5655
# flickr_username: jekyll
instagram_username: armannnnnny
linkedin_username: armantursun
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Arman Tursun and I am lucky to be an [Uyghur](https://en.wikipedia.org/wiki/Uyghurs#:~:text=The%20Uyghurs%20are%20recognized%20as,the%20titular%20people%20of%20Xinjiang.), ethnic minority in Central Asia, from [Ili](https://en.wikipedia.org/wiki/Ili_Kazakh_Autonomous_Prefecture) prefecture, China.

  My name is pronunced as /ɑːrmʌn tuːrsʊn/. Sometimes, you may see it written in Chinese pronunciation as Aerman Tuerxun, but I don't quite like it and I prefer Arman Tursun in the normal life.

  Currently, I am pursing my master's degree of computer science in [Tokyo](https://www.gotokyo.org/en/index.html), an amazing modern city full of life stress. I have been in Japan for over three years since I left the country. But I don't think I will spend the rest of my life here. The world is so wonderful, so why not go out and see it?


content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: University of Tokyo
        caption: Apr.2020 - Present
        sub_title: M.E Computer Science
        #quote: >
          #Established in 1636.
        description: | # this will include new lines to allow paragraphs
          2nd year master student of [Nakao Lab](https://www.nakao-lab.org/) in the [Graduate School of Interdisciplinary Information Science](https://www.iii.u-tokyo.ac.jp/). Supervised by Professor [Akihiro Nakao](https://www.sys.t.u-tokyo.ac.jp/en/memberpage/2151).

          I am broadly interested in networks and systems, more specifically in SDN; also like network analyzing using ML methods.

          My recent work is in the area of Network Sclicing, Local 5G, and Network Intelligence.
      - layout: left
        title: University of Tokyo
        caption: Apr.2019 - Mar.2020
        sub_title: Research Student
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I spent one year as research student in [Nakao Lab](https://www.nakao-lab.org/) working with Professor [Akihiro Nakao](https://www.sys.t.u-tokyo.ac.jp/en/memberpage/2151).

          During my time as research student, I was mainly preparing for my entrance exam as well as catching up most recent research in 5G.
      - layout: left
        title: University of Science and Technology of China
        caption: Sept.2014 - June.2018
        sub_title: B.E Information Security
        #quote: >
        #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          I got my B.E in [School of Information Science and Technology](https://en.sist.ustc.edu.cn/) at the [University of Science and Technology of China](http://en.ustc.edu.cn/)

          Graduation Thesis: Routing Algorithm in Disaster Relief Based on NDN Networks.

          I spent a wonderful 4 years with lovely classmates and friends.


  - title: Publication # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Design and Manufacture of Narrow-Band BPF for Local 5G Network Slicing
        #link: [pdf](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9492547)
        #link_text: [pdf](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9492547)
        #additional_links:
        #- title:  sproogen/modern-resume-theme
          #icon: fab fa-github
          #url: github.com/sproogen/modern-resume-theme
        #quote: >
          #Aerman Tuerxun, Ping Du, Junji Yumoto, Akihiro Nakao, 4th International Workshop on Advances in Slicing forSoftwarized Infrastructures, IEEE International Conference on Network Softwarization, 2021.
        description: | # this will include new lines to allow paragraphs
          Aerman Tuerxun, Ping Du, Junji Yumoto, Akihiro Nakao, 4th International Workshop on Advances in Slicing forSoftwarized Infrastructures, IEEE International Conference on Network Softwarization, 2021. [pdf](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9492547)

      - layout: top
        title: Analysis on Route Information Failure in IP Core Networks by NFV-Based Test Environment
        description: | # this will include new lines to allow paragraphs
          Fei Xia,Aerman Tuerxun, Jiaxing Lu. Ping Du, Akihiro Nakao, ITU Journal on Future and Evolving Technologiesspecial issue on AI and machine learning solutions in 5G and future networks, 2021.

      - layout: top
        title: Automatic Check-In Service at Businesses Enabled with Private Mobile Networks
        description: | # this will include new lines to allow paragraphs
            Ping Du,Aerman Tuerxun, Anan Sawabe, Takanori Iwai, Akihiro Nakao, IEEE Global CommunicationsConference (Globecom), 2020. [pdf](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=9348115)

      - layout: top
        title: MANET for Disaster Relief Based on NDN
        description: | # this will include new lines to allow paragraphs
            Yang Jin, Xiaobin Tan, Weiwei Feng, Jinyang Lv,Aerman Tuerxun, Kunpeng Wang, 2018 1st IEEE InternationalConference on Hot Information-Centric Networking (HotICN). IEEE, 2018. [pdf](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=8605969)

  - title: Research and Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: RF & Mircowave
        #link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: University of Tokyo
        caption: Sept.2020 - Present
        caption: Sept.2020 - Present
         # this will include new lines to allow paragraphs
        quote: >
          BPF Design and Implementing Using 3D Printing
        description: |
          Network slicing is considered one of the key technologies of the fifth-generation (5G) mobile networks. Especially in Local 5G networks, to ensure that one slice does not affect other slices, narrowband spectrum allocation appears to be
                    particularly important. Band Pass Filter (BPF) is one of the
                    most important components to isolate the spectrum resource of
                    each Local 5G RAN slice. However, it is difficult to buy a BPF
                    with a narrow band frequency on the market. Moreover, due
                    to complicated manufacturing procedures, the price of BPF is
                    usually very expensive, which increases the cost of establishing
                    a Local 5G base station for small enterprises. In our design,
                    we present a simple waveguide filter based on the theoretical
                    principles of a low-pass prototype of Chebyshev approximation.
                    The waveguide filter is designed with a center frequency at 4.75
                    GHz and narrow bandwidth of 100MHz. After simply forging
                    and evaluation, experimental results prove the feasibility of our
                    method in the processing of low-cost narrowband BPFs.
      - layout: left
        title: Network Analysis
        sub_title: University of Tokyo
        caption: July.2020 - Dec.2020
        description: Private mobile networks such as private LTE/local
              5G, which support flexibly configured and empowered innovative technologies that are not feasible in closed public mobile
              networks recently, have been catching much attention both
              in academia and in industries. In this paper, we design and
              implement the automatic check-in service as an example of valueadded services of private mobile networks utilizing the flexibility
              of softwarization. To alleviate the inherent coverage problem
              of a private mobile network, we integrate our private mobile
              network with a public LTE by sharing the subscriber database
              so that a user can use the automatic check-in services deployed
              in various private mobile networks with only one SIM issued
              by a public network. We perform field tests in a private mobile
              network and also a private-public hybrid mobile network and
              disclose that the users’ check-out behavior is predictable through
              numerical analyses. Based on the finding, we introduce two
              machine learning-based inference mechanisms that can predict
              a user’s check-out behavior at an inference accuracy of 83%
              and 93% in a private network and a hybrid one separately. We
              believe this paper can provide valuable experience for those who
              are developing their private mobile networks.


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and systems engineering some of my other interests and hobbies are:
      - Bodybuilding
      - Sports (Basketballs, Football, Soccer, F1, ...)
      - Men's Fragrances

      Look at this cool image  
      ![Trees](/cv/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
